spring.application.name=crudDemo

#
#JDBC Properties
#

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.password=springstudent
spring.datasource.username=springstudent

# to edit your path

spring.data.rest.base-path=/magic-api

# http://localhost:8080/magic-api/employees
