spring.application.name=crudDemo

#
#JDBC Properties
#

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.password=springstudent
spring.datasource.username=springstudent


# configure custom path for swagger
# instead of: http://localhost:8080/swagger-ui/index.html

# we will use: http://localhost:8080/ahmed-ui.html
springdoc.swagger-ui.path = /ahmed-ui.html

# to visit the docs json: localhost:8080/v3/api-docs
# if you want this in yaml: localhost:8080/v3/api-docs.yaml


# configure custom path for api docs
# instead of : localhost:8080/v3/api-docs

# we will use: localhost:8080/my-api-docs
spring.api-docs.path=/my-api-docs

